controller_manager:
  ros__parameters:
    update_rate: 100  

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    odradek_controller:
      type: joint_trajectory_controller/JointTrajectoryController

odradek_controller:
  ros__parameters:
    joints:
      - shoulder_yaw
      - shoulder_pitch
      - shoulder_roll
      - elbow_yaw
      - elbow_pitch
      - elbow_roll
      - wrist_roll
      - petal_1_inner_joint
      - petal_1_outer_joint
      - petal_2_inner_joint
      - petal_2_outer_joint
      - petal_3_inner_joint
      - petal_3_outer_joint
      - petal_4_inner_joint
      - petal_4_outer_joint
      - petal_5_inner_joint
      - petal_5_outer_joint
    
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: true   
